env:
  browser: true
  es2022: true
extends:
  - plugin:react/recommended
  - airbnb
  - next/core-web-vitals
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  semi: [error, never]
  arrow-body-style: off
  import/prefer-default-export: off
  max-len: off
  no-unused-vars: off
  '@typescript-eslint/no-unused-vars': error
  no-undef: off
  no-plusplus: [error, { allowForLoopAfterthoughts: true }]
  default-case: off
  no-case-declarations: off
  import/extensions: [
    error,
    ignorePackages,
    {
      ts: never,
      tsx: never,
    }
  ]
  jsx-quotes: [error, prefer-single]
  react/jsx-props-no-spreading: off
  react/jsx-filename-extension: [error, { extensions: ['.tsx'] }]
  react/function-component-definition: [error, { namedComponents: arrow-function }]
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: [
    warn, {
      additionalHooks: (useRecoilCallback|useRecoilTransaction_UNSTABLE) # https://recoiljs.org/docs/introduction/installation/#eslint
    }
  ]
