image: gitpod/workspace-full

tasks:
  - init: |
      npm install
      npm run build:wasm
      npm run dev
vscode:
  extensions:
    - matklad.rust-analyzer
    - bungcip.better-toml
    - serayuzgur.crates
    - EditorConfig.EditorConfig
