export const RECOIL_KEYS = {
  backgroundBrightness: 'backgroundBrightness',
  iterations: 'iterations',
  rectBrightnessMin: 'rectBrightnessMin',
  rectBrightnessMax: 'rectBrightnessMax',
  rectAlphaMin: 'rectAlphaMin',
  rectAlphaMax: 'rectAlphaMax',
  matrixBrightnessMin: 'matrixBrightnessMin',
  matrixBrightnessMax: 'matrixBrightnessMax',
  matrixAlphaMin: 'matrixAlphaMin',
  matrixAlphaMax: 'matrixAlphaMax',
  matrixColsMin: 'matrixColsMin',
  matrixColsMax: 'matrixColsMax',
  matrixRowsMin: 'matrixRowsMin',
  matrixRowsMax: 'matrixRowsMax',
  matrixSpacingPercent: 'matrixSpacingPercent',
}
