name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IS_DEVELOPMENT: ${{ github.event_name == 'pull_request' && github.ref != 'refs/heads/main' }}
  IS_PRODUCTION: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
  NETLIFY_SITE_NAME: 'xdisplacement'
  NETLIFY_DEVELOPMENT_DEPLOY_ID: ${{ github.sha }}

jobs:
  webassembly:
    name: WebAssembly
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
      RUST_TEST_THREADS: 32
    defaults:
      run:
        working-directory: wasm
    steps:
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - uses: actions/checkout@v3
    - name: Tests
      run: ./rs-test.sh
    - name: Code quality
      run: ./rs-clippy.sh
    - name: Code formatting
      run: ./rs-fmt.sh

  web:
    name: Web
    runs-on: ubuntu-latest
    steps:
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          ./wasm/target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
        cache-dependency-path: ./package-lock.json
    - name: Install dependencies
      run: npm ci
    - name: Build WebAssembly
      run: npm run build:wasm
    - name: Validate types
      run: npm run test:typescript
    - name: Code linting
      run: npm run test:lint
    - name: Build web application
      run: npm run build:web
    - uses: actions/upload-artifact@v3
      with:
        name: output
        path: ./out

  deploy:
    name: Deploy
    needs: [webassembly, web]  
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: netlify
    env:
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
        cache-dependency-path: ./netlify/package-lock.json
    - uses: actions/download-artifact@v3
      with:
        name: output
        path: ./netlify/out
    - name: Show "out" directory contents
      run: find ./out | sed -e "s/[^-][^\/]*\// |/g" -e "s/|\([^ ]\)/|-\1/"
    - name: Install dependencies for Netlify CLI
      run: npm ci
    - name: Deploy (Development)
      if: ${{ env.IS_DEVELOPMENT }}
      run: npx netlify deploy --dir=out --id ${{ env.NETLIFY_DEVELOPMENT_DEPLOY_ID }}
    - name: Deploy (Production)
      if: ${{ env.IS_PRODUCTION }}
      run: npx netlify deploy --dir=out --prod

  lighthouse:
    name: Lighthouse
    needs: [deploy]  
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: mkdir ./lighthouse-artifacts
    - name: Lighthouse (Development)
      if: ${{ env.IS_DEVELOPMENT }}
      uses: foo-software/lighthouse-check-action@master
      with:
        urls: 'https://${{ env.NETLIFY_DEVELOPMENT_DEPLOY_ID }}--${{ env.NETLIFY_SITE_NAME }}.netlify.app'
        outputDirectory: ./lighthouse-artifacts
        device: 'all'
        gitHubAccessToken: ${{ github.token }} # required for PR comments
        prCommentEnabled: true
        prCommentSaveOld: true
    - name: Lighthouse (Production)
      if: ${{ env.IS_PRODUCTION }}
      uses: foo-software/lighthouse-check-action@master
      with:
        urls: 'https://${{ env.NETLIFY_SITE_NAME }}.netlify.app'
        outputDirectory: ./lighthouse-artifacts
        device: 'all'
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: lighthouse
        path: ./lighthouse-artifacts
